CREATE USER kf_download_test IDENTIFIED BY kf_download_test;
GRANT CREATE SESSION TO kf_download_test;
GRANT ALL PRIVILEGES TO kf_download_test;

CREATE TABLE "KF_DOWNLOAD_TEST"."SMGROUP"
("OGR_FID" NUMBER(*, 0),
 "GROUPID" VARCHAR2(2047),
 "NAME"    VARCHAR2(2047)
);
CREATE TABLE "KF_DOWNLOAD_TEST"."SMUSER"
("OGR_FID"         NUMBER(*, 0),
 "USERID"          VARCHAR2(2047),
 "NAME"            VARCHAR2(2047),
 "PASSWORD"        VARCHAR2(2047),
 "LASTNAME"        VARCHAR2(2047),
 "FIRSTNAME"       VARCHAR2(2047),
 "EMAILADDRESS"    VARCHAR2(2047),
 "TELEPHONENUMBER" VARCHAR2(2047),
 "DISABLED"        VARCHAR2(2047),
 "DEBITORNO"       VARCHAR2(2047),
  CONSTRAINT "SMUSER_USERID_UNIQUE" UNIQUE ("USERID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE (INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
    TABLESPACE "USERS" ENABLE
);
CREATE TABLE "KF_DOWNLOAD_TEST"."SMUSERGROUP"
("OGR_FID" NUMBER(*, 0),
 "ID"      VARCHAR2(2047),
 "GROUPID" VARCHAR2(2047),
 "USERID"  VARCHAR2(2047)
);
CREATE TABLE "KF_DOWNLOAD_TEST"."SMUSER_EXTRA"
("OGR_FID"            NUMBER(*, 0),
 "DUID"               VARCHAR2(2047),
 "USERID"             VARCHAR2(2047),
 "USERTYPE"           VARCHAR2(2047),
 "USERTYPE_INFO"      VARCHAR2(2047),
 "RECEIVE_NEWSLETTER" VARCHAR2(2047),
 "ACCEPT_TERMS"       VARCHAR2(2047),
 "CONTACT_ME"         VARCHAR2(2047),
 "MASTER_USERID"      VARCHAR2(2027),
  CONSTRAINT "SMUSER_EXTRA_USERID_UNIQUE" UNIQUE ("USERID")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
    STORAGE (INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
    TABLESPACE "USERS" ENABLE
);