CREATE USER weblog_test IDENTIFIED BY weblog_test;
GRANT CREATE SESSION TO weblog_test;
GRANT ALL PRIVILEGES TO weblog_test;

 TABLE "WEBLOG_TEST"."SERVICES2"
("SERVICEID"      NUMBER(*, 0),
 "TYPEID"         NUMBER(*, 0),
 "SERVICENAME"    VARCHAR2(50),
 "SERVICETITLE"   VARCHAR2(200),
 "ABSTRACT"       VARCHAR2(2000),
 "QUIRKS"         NUMBER,
 "INCLUDEDINDEMO" NUMBER(*, 0),
 "ISRASTER"       NUMBER(1, 0),
 "ISPRINT"        NUMBER(1, 0),
 "CATEGORYIDS"    VARCHAR2(50)
);
CREATE TABLE "WEBLOG_TEST"."SERVICETYPES2"
("TYPEID"    NUMBER(*, 0),
 "TYPENAME"  VARCHAR2(50),
 "TYPETITLE" VARCHAR2(50)
);
CREATE TABLE "WEBLOG_TEST"."USERRESTRICTIONS2"
("SERVICEID"      NUMBER(*, 0),
 "USERID"         VARCHAR2(50),
 "MINX"           NUMBER,
 "MINY"           NUMBER,
 "MAXX"           NUMBER,
 "MAXY"           NUMBER,
 "MAXPIXELWIDTH"  NUMBER,
 "MAXPIXELHEIGHT" NUMBER,
 "FEATUREINFO"    NUMBER(*, 0),
 "DRUPALID"       NUMBER(*, 0)
);